### ISSUE TITLE
https://www.topydo.org/ not available

### ISSUE THREAD

**Issue by HaaiHenkie** [topydo/topydo#244]
Hello,

I would you like to know that the website https://www.topydo.org/ is not available.

Cheers,

Henk

**Comment by jbrodriguez** [comment]
Can anyone edit README.md to point to the new address ?

It doesn't redirect in my case.

**Comment by maxrodrigo** [comment]
The link in the repo description should be update too.

**Comment by jbrodriguez** [comment]
A heads up ... rawgit is shutting down.

News at https://rawgit.com/

**Comment by sebastiaanspeck** [comment]
@bram85 maybe it is an option to switch to GitHub Pages instead

**Comment by valvin1** [comment]
issue is still present old link is present in README.md and project descrption.

**Comment by bram85** [comment]
I'm in the process of trying to set up Github pages.

**Comment by bacardi55** [comment]
In the meantime, if people like are trying to find the doc, there is an archive version here:
https://web.archive.org/web/20180831061945/https://cdn.rawgit.com/bram85/topydo/master/doc/Documentation.html

**Comment by RonCam** [comment]
@bacardi55 , this is good news and thanks for posting.
I note this is available courtesy of the _WayBack Machine_.  I wonder, how long this will remain available, since it's not under the direct control of the topydo developers?
Will this site keep the archive available indefinitely?  If that's not a sure thing, then it seems it's time for topydo users to download the documentation, on local storage.
Can @bram85  post a currently-active link for that?

**Comment by RonCam** [comment]
Well, it's resolved, and many thanks to @bacardi55 for posting the link, because I now have a copy of the documentation on a flash drive.  I do feel better, knowing I'm OK -- while waiting for [the proposed online documentation relocation](https://github.com/bram85/topydo/issues/244#issuecomment-472488374) to materialize.
For other _topydo_ users who are 'in the same boat' as I was, here's what I did:

1. Open the _Waybackmachine_ link, as was kindly provided by @bacardi55 .
2. Remove the Waybackmachine banner (may or may not be a necessary step)..
3. Click the _Tools_ tab, then activate the **[x]** on _Save Changes._
4. Click on the _Open_ tab. Note, _Save Changes_ is now visible on this page's menu as a _red-circled check-mark_.
5. Click on that check-mark, and this is _after_ the _Open_ tag has been selected.  Otherwise, your copy will open with _Tools_ selected.
6. Save in _Static HTML_ format.  In the save file dialog, the html file will have the name of _Documentation_. 
7. If it saves in a different format, you may have to make a selection in _Export All_, first.
8. Save to whatever location you wish -- pick the local storage location of your choice.
9. In your file manager, select the Documentation file you just saved.
10. Right-click to get _Context Menu_, and then _Open with_ -- select browser of your choice.
11. Hit _Enter_ and wait a bit, for the topydo documentation's Welcome page to appear.

If _Save Changes_ doesn't work, you may have to do an _Export_ first.  I think there's a bug here because it's non-intuitive.  If not sure, save more than once, then use whichever file has the larger file-size.

Now, it's no longer necessary to be online to read the documentation. It's only 2.3Mb -- thought it would be far larger.  It's time-stamped the 30th of January 2018 at 12:10pm.

**Comment by rnkn** [comment]
Hey @RonCam there's a much easier way. Simply download https://github.com/bram85/topydo/raw/master/docs/index.html and double-click.

Or, put it in a folder and `python3 -m http.server -d FODLER`.

**Comment by RonCam** [comment]
Hi @rnkn !  
Good job, and yes, that was far fewer steps.  I used the first method in your post.
I wanted to follow your directions and see github's copy because I wasn't sure if the _Waybackmachine_ was displaying the latest (or, perhaps I should say, the final?) version.
Both are time-stamped identically: 30th January 2018 at 12:10pm.  So now, no more _angst_ over being in the middle of a _topydo_ session, having to check something in the ducumentation, and not being able to do it!

**Comment by RonCam** [comment]
Having a local copy of the documentation is working well, with advantages of its own.  If I am having difficulty with remembering a certain point (Dependencies, as an example) I am finding that a minor rewording, or restating, can now be saved for my future reference.  This, of course, is not possible when accessing the documentation on-line.

**Comment by adityabhaskar** [comment]
For reference, I hosted a copy of the documentation till the original comes up...  https://c306.net/t/topydo-docs/

**Comment by davesteele** [comment]
Resolved
