### ISSUE TITLE
configurable time/date presentation formating 

### ISSUE THREAD

**Issue by ruru4143** [topydo/topydo#282]
A configurable time/date presentation formatting would be nice. 
The most people aren't used to YMD as you can see here: [wikipedia](https://en.wikipedia.org/wiki/Date_format_by_country) 

I can think of two solutions:
1. A configuration variable that is able to change order and seperator of the date format

`date_format = YYYY-MM-DD` (`2020-11-23` default)
`date_format = YYYY/MM/DD` (`2020/11/23`)
`date_format = DD.MM.YYYY` (`23.11.2020` my preference)

2. A configuration variable that reads Python's strftime codes.

`date_format = %Y-%m-%d` (`2020-11-23` default)
`date_format = %d.%m.%Y` (`23.11.2020` my preference)
with this option, it would also be possible to configure weekdays etc
`date_format = %a %Y-%m-%d` (`Mon 2020-11-23`)

let me know what you think about the idea and if you would merge it.

**Comment by mruwek** [comment]
`YYYY-MM-DD` is a part of todo.txt spec so we can discuss only changes in date presentation.  Values saved/read from `todo.txt` have to follow the spec to maintain compatibility with other apps.

**Comment by ruru4143** [comment]
@mruwek okey, i missed that (i only read this for reference https://github.com/todotxt/todo.txt ).

**Comment by btittelbach** [comment]
- on the one hand: supporting different representations would certainly make topydo more accessible to users
- on the other hand: 
  - the different date formats would also have to be parsed when adding new todo's
  - should the global locale be read to display the date in the local format? Or should it be a local option that is then forgotten or configured extra?
  - todo.txt is designed to be editable by hand and it may lead to mistakes and confusion if the date format inside todo.txt is iso, while the date format displayed by topydo is parsed and used differently.
  - Since different date formats may look the same, it's not even possible to use iso-parsing as fallback e.g. YYYY-MM-DD vs YYYY-DD-MM


Disclamer: I love the ISO-Date and think it's the international standard for good reason and we would all be happier if everybody would learn and use ISO-Date rather than the confusing local variations we are spoilt with in school.
